### ISSUE TITLE
启动时报错

### ISSUE THREAD

**Issue by purofle** [rabbitkiller-dev/discord-qq-bridge#35]
```
[10:47:40 PM] Starting compilation in watch mode...

[10:47:47 PM] Found 0 errors. Watching for file changes.

/home/ssx/discord-qq-bridge/node_modules/@yunyoujun/logger/dist/logger.js:16
    options;
           ^
                                                                                        SyntaxError: Unexpected token ;
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)                at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)                         at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)                                      at Object.<anonymous> (/home/ssx/discord-qq-bridge/node_modules/@yunyoujun/logger/dist/index.js:7:34)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
```

**Comment by rabbitkiller-dev** [comment]
用的是什么命令启动, node版本是多少

**Comment by purofle** [comment]
启动命令是npm&nbsp;run&nbsp;start:dev
版本是v10.19.0
系统是ubuntu20.04


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月31日(周二) 凌晨0:13
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [rabbitkiller-dev/discord-qq-bridge] 启动时报错 (#35)




 
用的是什么命令启动, node版本是多少
 
&mdash;

**Comment by rabbitkiller-dev** [comment]
@purofle 看了下, 目前最低需要node-v12.0.0版本以上的, 以防万一的话最好和我使用相同的版本, v14以上

**Comment by purofle** [comment]
> @purofle 看了下, 目前最低需要node-v12.0.0版本以上的, 以防万一的话最好和我使用相同的版本, v14以上

出现了新的报错：
```
Error [DISALLOWED_INTENTS]: Privileged intent provided is not enabled or whitelisted.
    at WebSocketManager.createShards (/home/ssx/discord-qq-bridge/node_modules/discord.js/src/client/websocket/WebSocketManager.js:258:15)
    at async Client.login (/home/ssx/discord-qq-bridge/node_modules/discord.js/src/client/Client.js:223:7) {
  [Symbol(code)]: 'DISALLOWED_INTENTS'
}
```

**Comment by rabbitkiller-dev** [comment]
> 出现了新的报错：
> 
> ```
> Error [DISALLOWED_INTENTS]: Privileged intent provided is not enabled or whitelisted.
>     at WebSocketManager.createShards (/home/ssx/discord-qq-bridge/node_modules/discord.js/src/client/websocket/WebSocketManager.js:258:15)
>     at async Client.login (/home/ssx/discord-qq-bridge/node_modules/discord.js/src/client/Client.js:223:7) {
>   [Symbol(code)]: 'DISALLOWED_INTENTS'
> }
> ```
这似乎是来自discord服务器的报错. 
我也不太清楚具体是哪里出来的, 你看一下和我的配置是否一致
![image](https://user-images.githubusercontent.com/28952169/131381316-93346c44-ee96-4b96-8cc6-e8a1c7eaffd3.png)

**Comment by WinstonSung** [comment]
@purofle 
另外，方便询问一下拉取的分支是哪一个吗？

**Comment by purofle** [comment]
修改配置后已经可以使用，用的是master分支


---原始邮件---
发件人: &quot;Winston ***@***.***&gt;
发送时间: 2021年8月31日(周二) 凌晨1:52
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [rabbitkiller-dev/discord-qq-bridge]启动时报错 (#35)




 
@purofle
 另外，方便询问一下拉取的分支是哪一个吗？
 
&mdash;
